In [2]:
import pandas as pd
file_path = '../excel/지방세징수(구별)_20231203000721.xlsx'

In [3]:
df = pd.read_excel(file_path, header=3)
# Unnamed:0을 -> 자치구로변경
df.rename(columns={'Unnamed: 0': '자치구'}, inplace=True)
df.head()

,자치구,소계,소계.1,소계.2,취득세,레저세,주민세,자동차세,담배소비세,재산세,...,재산세.1,종합토지세,면허세,지방소득세.1,지방소비세.1,지역자원시설세,지방교육세,사업소세,소계.3,소계.4
0,소계,30711730,26163798,4547932,5871174,105142,727769,1025804,588594,3918885,...,3824165,0,0,-,228918,325408,1789798,-,215570,19261
1,소계,4058281,4058281,-,9769,-,420,399766,588594,-,...,-,-,-,-,-,-,259176,-,42859,-
2,종로구,1330953,1171416,159537,240378,3647,59046,9706,-,120640,...,138531,-,-,-,4779,13488,53000,-,3393,608
3,중구,2077957,1873231,204725,238006,2483,84197,13522,-,175979,...,169504,-,-,-,3025,22890,67451,-,5103,1258
4,용산구,1239147,1041605,197541,299807,126,23571,16663,-,174193,...,167858,-,-,-,5978,10386,69633,-,5260,970

In [4]:
# '자치구'와 '재산세' 컬럼 선택
selected_columns = df[['자치구', '재산세']]
selected_columns

     자치구      재산세
0     소계  3918885
1     소계        -
2    종로구   120640
3     중구   175979
4    용산구   174193
5    성동구   129470
6    광진구    91078
7   동대문구    83483
8    중랑구    55558
9    성북구    88919
10   강북구    40096
11   도봉구    43136
12   노원구    80626
13   은평구    81046
14  서대문구    78211
15   마포구   165098
16   양천구   124773
17   강서구   140707
18   구로구    86407
19   금천구    56772
20  영등포구   183229
21   동작구   104949
22   관악구    76845
23   서초구   439657
24   강남구   765111
25   송파구   381796
26   강동구   151105

In [5]:
#자치구에서 소계 두줄 제거
property_tax = selected_columns[selected_columns['자치구'] != '소계']
#원본유지를위해 복사본생성
property_tax_copy = property_tax.copy()
#내림차순정렬
property_tax_copy.sort_values(by='재산세', ascending=False, inplace=True)
#재산세에 1000으로나눔
property_tax_copy['재산세'] = (property_tax_copy['재산세'] / 1000).astype(int)
property_tax = property_tax_copy
# 결과 확인
property_tax

     자치구  재산세
24   강남구  765
23   서초구  439
25   송파구  381
20  영등포구  183
3     중구  175
4    용산구  174
15   마포구  165
26   강동구  151
17   강서구  140
5    성동구  129
16   양천구  124
2    종로구  120
21   동작구  104
6    광진구   91
9    성북구   88
18   구로구   86
7   동대문구   83
13   은평구   81
12   노원구   80
14  서대문구   78
22   관악구   76
19   금천구   56
8    중랑구   55
11   도봉구   43
10   강북구   40