In [1]:
import pandas as pd

In [2]:
file_path = '../../excel/지방세징수(구별)_20231203000721.xlsx'
df = pd.read_excel(file_path, header=3)
df.rename(columns={'Unnamed: 0': '자치구'}, inplace=True)
selected_columns = df[['자치구', '재산세']]
property_tax = selected_columns[selected_columns['자치구'] != '소계']
property_tax_copy = property_tax.copy()
property_tax_copy.sort_values(by='재산세', ascending=False, inplace=True)
property_tax_copy['재산세'] = (property_tax_copy['재산세'] / 1000).astype(int)
property_tax = property_tax_copy
print(property_tax)

     자치구  재산세
24   강남구  765
23   서초구  439
25   송파구  381
20  영등포구  183
3     중구  175
4    용산구  174
15   마포구  165
26   강동구  151
17   강서구  140
5    성동구  129
16   양천구  124
2    종로구  120
21   동작구  104
6    광진구   91
9    성북구   88
18   구로구   86
7   동대문구   83
13   은평구   81
12   노원구   80
14  서대문구   78
22   관악구   76
19   금천구   56
8    중랑구   55
11   도봉구   43
10   강북구   40

In [3]:
#유기동물데이터
file_path = '../../excel/유기동물.xlsx'
df = pd.read_excel(file_path)
df.head()
abandoned_animals = df[['자치구별(2)', 2022]].iloc[4:]
abandoned_animals.rename(columns={'자치구별(2)': '자치구', 2022: '유기동물수'}, inplace=True)
abandoned_animals.head(10)

     자치구 유기동물수
4    용산구   238
5    성동구   165
6    광진구   167
7   동대문구   201
8    중랑구   199
9    성북구   168
10   강북구   270
11   도봉구   137
12   노원구   215
13   은평구   273

In [4]:
#데이터합치기 '자치구' 기준
merged_df = pd.merge(property_tax, abandoned_animals, on='자치구')

# 결과 출력
merged_df

     자치구  재산세 유기동물수
0    강남구  765   147
1    서초구  439   130
2    송파구  381   173
3   영등포구  183   152
4    용산구  174   238
5    마포구  165   286
6    강동구  151   284
7    강서구  140   222
8    성동구  129   165
9    양천구  124   189
10   동작구  104   224
11   광진구   91   167
12   성북구   88   168
13   구로구   86   180
14  동대문구   83   201
15   은평구   81   273
16   노원구   80   215
17  서대문구   78   120
18   관악구   76   298
19   금천구   56   148
20   중랑구   55   199
21   도봉구   43   137
22   강북구   40   270

In [8]:
json_file_path = '../../json/재산세(내림)+유기동물.json'
merged_df.to_json(json_file_path, orient='records', force_ascii=False)

# # 저장된 파일 경로 반환
json_file_path

'../../json/재산세(내림)+유기동물.json'